### ISSUE TITLE
Treinamento 2 - Git, Kanban e Docker

### ISSUE THREAD

**Issue by eliseuegewarth** [fga-gpp-mds/AGR-APP-react-native#8]
Esse treinamento tem como objetivo apresentar conceitos básicos sobre as ferramentas Git, Kanban e Docker.
O versionamento de código e a configuração automatizada de ambiente serão utilizadas ao longo de todo o projeto e o gerenciamento das tarefas será acompanhado via ZenHub como nosso Kanban.

# Conteúdo:

- O que é **Kanban**?
- Como usaremos o **Kanban**?
- O que é **Docker** ?
- O que é **Git**?
- Comandos Básicos **Git**
- **Git Flow**
- Convenções sobre issues, pull requests
- Convenções sobre **commits**
- Comandos Básicos **Docker**

Data: 17 / 03 às 9h
Local : Gama

**Comment by alvesisaque** [comment]
Pauta:
Git, Kanban.

@gag2502 não pode estar presente.
